enum ActionTypes {
  MODEL_RUN_REQUESTED = 'MODEL_RUN_REQUESTED',
  MODEL_RUN_COMPLETED = 'MODEL_RUN_COMPLETED',
  MODEL_RUN_IMAGE_PROCESS_REQUESTED = 'MODEL_RUN_IMAGE_PROCESS_REQUESTED',
  MODEL_RUN_IMAGE_PROCESS_COMPLETED = 'MODEL_RUN_IMAGE_PROCESS_COMPLETED',
}

export default ActionTypes;
